services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - 'MONGO_INITDB_DATABASE=services'
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpass'
      - 'MONGO_INITDB_ROOT_USERNAME=rootuser'
      - 'MONGO_UUID_REPRESENTATION=standard'
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb-data:/data'
  axonserver:
    image: 'axoniq/axonserver'
    container_name: 'axonserver'
    hostname: 'axonserver'
    volumes:
      - 'axonserver-data:/data'
      - 'axonserver-events:/eventdata'
      - 'axonserver-config:/config:ro'
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
  sonarqube:
    image: sonarqube:community
    container_name: 'sonarqube'
    depends_on:
      - postgresql
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  postgresql:
    image: postgres:12
    container_name: 'postgresql'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
  mongodb-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: