spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:services}
      uri: mongodb://${MONGODB_USERNAME:rootuser}:${MONGODB_PASSWORD:rootpass}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/${MONGODB_DATABASE:services}?authSource=admin&uuidRepresentation=standard
  docker:
    compose:
      file: ./services.web/docker-compose.yaml
      enabled: false
  jackson:
    date-format: org.domivice.services.openapi.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  profiles:
    active: local
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://api.auth.domivice.dev/.well-known/openid-configuration/jwks
          issuer-uri: https://api.auth.domivice.dev
          audiences: services.api
axon:
  serializer:
    events: jackson
    general: jackson
    messages: jackson
logging:
  level:
    org.domivice.services: DEBUG
    org.springframework.security: DEBUG